<?php


namespace Alexx\HelloWorldPlugins\Test\Unit\Plugin;


use Alexx\HelloWorld\Model\Hello;
use Alexx\HelloWorldApi\Api\Data\HelloApiInterface;
use Alexx\HelloWorldPlugins\Plugin\PluginBefore;

class PluginBeforeTest extends \PHPUnit\Framework\TestCase
{
    private $parentObject;

    private $pluginObject;

    protected function setUp()
    {
        $this->pluginObject = new PluginBefore();
        $this->parentObject = new Hello();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testInstance()
    {
        $this->assertInstanceOf(PluginBefore::class, $this->pluginObject);
    }

    public function testImplementsHelloApiInterface()
    {
        $this->assertInstanceOf(HelloApiInterface::class, $this->parentObject);
    }


    public function testBefore()
    {
        $inStr = __('Hello world')->__toString();
        $outStr = 'prefix_' . $inStr ;

        $this->assertEquals($inStr, $this->parentObject->getHello());



        $this->assertEquals($outStr, $this->pluginObject->afterGetHello($this->parentObject, $inStr));
    }
}
