<?php
/**@var $block \Alexx\Blog\Block\BlogList */

if ($block->isBlogIsEnabled()) {
    $posts = $block->getPosts();
    if (count($posts) > 0) { ?>
        <div class="blogs-applied-to-category">
            <h2><?= $block->escapeHtml(__('Blog posts')) ?></h2>
            <?php foreach ($posts as $post) { ?>
                <div class="blog-card">
                    <div>
                        <img src="<?= $block->escapeUrl($post->getImageUrl()) ?>">
                    </div>
                    <span><?= $block->escapeHtml($post->getTheme()) ?></span>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
<?php } ?>
