<?php
/**@var $block \Alexx\Blog\Block\BlogList */


if ($block->isBlogEnabled()):
    $posts = $block->getLastPosts();
    if (count($posts) > 0): ?>
        <div class="blogs-applied-to-category">
            <h2><?= $block->escapeHtml(__('Blog posts')) ?></h2>
            <?php foreach ($posts as $post): ?>
                <?php /**@var \Alexx\Blog\Api\Data\BlogInterface $post */ ?>
                <div class="blog-card">
                    <div>
                        <img src="<?= $block->escapeUrl($block->getPictureUrl($post)) ?>">
                    </div>
                    <span><?= $block->escapeHtml($post->getTheme()) ?></span>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
