<?php
/**@var $block \Alexx\Description\Block\ProductBlock */
if ($block->isDescriptionAddAllowed()):
    /**@var \Alexx\Description\Api\Data\DescriptionInterface */
    $descriptionData = $block->getClientDescription();
    ?>
    <div id="responsemessage"></div>
    <a id="show-form-trigger"><?= $block->escapeHtml(__('Show form')) ?></a>
    <a id="delete-trigger"><?= $block->escapeHtml(__('Delete description')) ?></a>

    <form id="customer-description-form">
        <input type="hidden"
               name="product_entity_id"
               value="<?= $block->escapeHtml($descriptionData->getProductEntityId()); ?>"
        >
        <textarea name="description" id="ajaxcallvalue"><?= $block->escapeHtml($descriptionData->getDescription()); ?>
        </textarea>
        <input type="submit" id="ajaxcall">
    </form>
    <script>
        require(['AlexxDescription'], function (AlexxDescription) {
            AlexxDescription(<?= $block->escapeHtml(strlen($descriptionData->getDescription())) ?>);
        });
    </script>
    <?php
endif;
